/* Trusted facts and competing explanations are rendered separately from model inference. */
window.HypothesisPanel=(()=>{
  let reports=[],selectedIncident=null,selectedHypothesis=null,busy=false;
  const el=id=>document.getElementById(id);
  const statuses={plausible:'Plausible, unverified',supported:'Supported by evidence',weak:'Weak support',contradicted:'Contradicted by evidence',insufficient_evidence:'Insufficient evidence'};
  const stops={not_run:'Not investigated',all_answerable_checked:'Answerable questions completed',tool_budget_exhausted:'Tool budget exhausted',unavailable_telemetry:'Additional telemetry required',no_new_distinguishing_evidence:'No new distinguishing evidence',iteration_limit:'Single-round limit reached'};
  function refs(ids){return ids.length?ids.map(evidenceButton).join(' '):'<span class="no-evidence">No direct evidence in this category</span>'}
  function current(){return reports.find(r=>r.incident_id===selectedIncident)}
  function setBusy(value){busy=value;document.querySelectorAll('.investigation-action').forEach(button=>{button.disabled=busy||button.dataset.unavailable==='true'})}
  function applyGraphFocus(){const report=current();if(!report)return;const h=report.hypotheses.find(h=>h.id===selectedHypothesis);if(h)SecurityGraph.highlight(h);else SecurityGraph.selectScope(report.incident_id)}
  function render(){
    const report=current(),container=el('hypothesis-cards');
    el('read-investigate').dataset.unavailable=el('ai-investigate').dataset.unavailable=String(!report);
    if(!report){container.textContent='No incidents. Benign traffic does not automatically produce attack hypotheses.';el('observed-facts').replaceChildren();el('investigation-questions').replaceChildren();el('investigation-stop').textContent='';el('missing-evidence').replaceChildren();setBusy(busy);return}
    el('observed-facts').innerHTML=`<h3>Observed facts (derived from logs by the backend)</h3><ul>${report.observed_facts.map(f=>`<li>${escapeHtml(f.text)}<div>${refs(f.evidence_ids)}</div></li>`).join('')}</ul>`;
    container.innerHTML=report.hypotheses.map(h=>`<article class="hypothesis-card ${h.id===selectedHypothesis?'focused':''}"><button class="hypothesis-select" data-hypothesis="${escapeHtml(h.id)}"><strong>${escapeHtml(h.title)}</strong><span class="hypothesis-status ${h.status}">${escapeHtml(statuses[h.status]||h.status)}</span><b>Evidence support score ${h.confidence.toFixed(2)}</b></button><p>${escapeHtml(h.description)}</p><small>${h.confidence_origin==='rule'?'Initial rule assessment':'AI comparison, bounded by evidence limits'} · not a compromise probability</small><details><summary>Supporting / contradicting / neutral evidence</summary><h4>Supporting (compatible with this explanation, not proof)</h4>${refs(h.supporting_evidence_ids)}<h4>Contradicting</h4>${refs(h.contradicting_evidence_ids)}<h4>Neutral</h4>${refs(h.neutral_evidence_ids)}</details><h4>Missing evidence</h4><ul>${h.missing_evidence.map(v=>`<li>${escapeHtml(v)}</li>`).join('')}</ul><h4>Inference (unverified)</h4><p>${escapeHtml(/[\u4e00-\u9fff]/.test(h.inference)?'This inference was saved in the earlier language. Run AI comparison for an English version.':h.inference)}</p>${refs(h.inference_evidence_ids||[])}</article>`).join('');
    container.querySelectorAll('[data-hypothesis]').forEach(button=>button.addEventListener('click',()=>{selectedHypothesis=button.dataset.hypothesis;render();applyGraphFocus()}));
    el('missing-evidence').innerHTML=`<h3>What remains unresolved</h3><p>${escapeHtml(report.uncertainty)}</p><ul>${report.missing_evidence.map(v=>`<li>${escapeHtml(v)}</li>`).join('')}</ul>`;
    el('investigation-questions').innerHTML=`<h3>Investigation questions</h3>${report.questions.map(q=>`<article class="question-row"><div><strong>${escapeHtml(q.question)}</strong><small>${q.answerable?'Answerable using this scan':'Missing '+escapeHtml(q.evidence_type)+' telemetry'}</small><p>${escapeHtml(q.answer||'Not queried yet')}</p>${q.evidence_ids.length?refs(q.evidence_ids):''}${q.truncated?'<p class="query-truncated">Results are truncated and do not represent all activity.</p>':''}</div><button class="investigation-action" data-question="${escapeHtml(q.id)}" data-unavailable="${!q.answerable||q.status==='answered'}">${!q.answerable?'Data unavailable':q.status==='answered'?'Checked':'Read-only query'}</button></article>`).join('')}`;
    el('investigation-questions').querySelectorAll('[data-question]').forEach(button=>button.addEventListener('click',()=>runSelectedIncident(false,[button.dataset.question])));
    el('investigation-stop').innerHTML=`<h3>Investigation status: ${escapeHtml(stops[report.stop_reason]||report.stop_reason)}</h3><p>${escapeHtml(report.stop_explanation)}</p><p>This round ${report.tool_calls} / ${report.tool_budget} tool calls · ${report.iteration_count} / 1 query rounds</p><p>${escapeHtml(report.confidence_note)}</p>`;
    [container,el('observed-facts'),el('investigation-questions')].forEach(bindEvidence);
    setBusy(busy);
  }
  function setData(data,preferred){reports=data||[];selectedIncident=reports.some(r=>r.incident_id===preferred)?preferred:(reports.some(r=>r.incident_id===selectedIncident)?selectedIncident:reports[0]?.incident_id||null);selectedHypothesis=null;const select=el('hypothesis-incident');select.replaceChildren();reports.forEach(report=>{const option=document.createElement('option');option.value=report.incident_id;option.textContent=report.incident_id;select.append(option)});select.value=selectedIncident||'';render();applyGraphFocus()}
  function replaceReport(report){reports=reports.map(r=>r.incident_id===report.incident_id?report:r);selectedIncident=report.incident_id;el('hypothesis-incident').value=selectedIncident;render();applyGraphFocus()}
  function chooseIncident(id){if(!reports.some(r=>r.incident_id===id))return;selectedIncident=id;selectedHypothesis=null;el('hypothesis-incident').value=id;render();applyGraphFocus()}
  function init(){el('hypothesis-incident').addEventListener('change',event=>{chooseIncident(event.target.value);selectInvestigationIncident(event.target.value,false)});el('read-investigate').addEventListener('click',()=>runSelectedIncident(false));el('ai-investigate').addEventListener('click',()=>runSelectedIncident(true));render()}
  return {init,setData,replaceReport,setBusy,applyGraphFocus,chooseIncident,selectedId:()=>selectedIncident};
})();
